services:
  stremio-meta-search:
    image: ghcr.io/ljstadler/stremio-meta-search
    environment:
      - TMDB_API_ACCESS_TOKEN=${TMDB_API_ACCESS_TOKEN}
      - TVDB_API_KEY=${TVDB_API_KEY}
    ports:
      - 8080:8080
